name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
    branches:
      - main

jobs:
  check-changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -aFl /home/runner/work/vivid-3/vivid-3
          node ./test.js
